[project]
name = "stt-src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "librosa>=0.11.0",
    "numpy>=2.3.5",
    "openai>=2.15.0",
    "torch>=2.8.0",
    "transformers>=4.57.6",
]
