[project]
name = "sec01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "openai>=2.15.0",
    "pytz>=2025.2",
    "streamlit>=1.53.1",
]
