services:
  guac-postgres:
    image: postgres:18.0
    container_name: guac-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guac-network

  guac-guacd:
    image: guacamole/guacd:1.6.0
    container_name: guac-guacd
    restart: unless-stopped
    ports:
      - "4822:4822"
    networks:
      - guac-network

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    restart: unless-stopped
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DATABASE: guacamole_db
      GUACD_HOSTNAME: guac-guacd
      POSTGRES_HOSTNAME: guac-postgres
    ports:
      - "51234:8080"
    networks:
      - guac-network


networks:
  guac-network:
